### ISSUE TITLE
Use bitvec v.1+ instead of bitvec v0.22.3 which is broken

### ISSUE THREAD

**Issue by benhadad** [spacemeowx2/blflash#14]
bitvec v0.22.3 has the dependency of funty v1.2.0 which has been yanked.  There is currently no additional support for bitvec 0.22 versions. The author says to move to 1.0 or higher of bitvec.

It seems to make sense to also update the deku version as it also reference bitvec.

Current is deku v0.12 -> bitvec v0.22.3->funty v1.2.0
New is  deku v0.15.0+->bitvec v1.0.1+->funty v2.0.0

**Comment by spacemeowx2** [comment]
#15
